prestation edit and update
WildCodeSchool/orleans-php-202103-project-voyante pull request #111
Opened 2021-04-28 15:15 UTC by Vannou28

2021-04-28 15:44 UTC, RaphaelBS-WCS approved these changes
Approved

2021-04-28 23:54 UTC, Mcbess-san submitted a review, later dismissed

2021-04-29 13:13 UTC, Erdnaxela45 approved these changes

2021-04-29 13:21 UTC, LucyMerlier requested changes
see comment

2021-04-29 13:21 UTC, LucyMerlier commented on src/Controller/AdminController.php
> +
TODO : form validations

2021-04-29 13:24 UTC, LucyMerlier approved these changes

2021-04-29 13:24 UTC, merged