S3 us12 services add form
WildCodeSchool/orleans-php-202103-project-voyante pull request #112
Opened 2021-04-28 15:38 UTC by RaphaelBS-WCS

2021-04-28 16:00 UTC, Vannou28 approved these changes

2021-04-28 20:22 UTC, Vannou28 submitted a review, later dismissed

2021-04-29 10:11 UTC, LucyMerlier requested changes
see comment

2021-04-29 10:11 UTC, LucyMerlier commented on src/Controller/AdminController.php
> +    public function addService()
method need return typehint

2021-04-29 13:16 UTC, Erdnaxela45 approved these changes

2021-04-29 13:22 UTC, LucyMerlier approved these changes

2021-04-29 13:38 UTC, Erdnaxela45 approved these changes

2021-04-29 13:57 UTC, LucyMerlier approved these changes

2021-04-29 13:58 UTC, merged