conflict error
WildCodeSchool/orleans-php-202103-project-voyante pull request #116
Opened 2021-04-28 20:55 UTC by Vannou28

error when selecting conflics that's why we review this pull request

2021-04-28 23:48 UTC, Mcbess-san approved these changes

2021-04-29 13:19 UTC, Erdnaxela45 approved these changes

2021-04-29 13:25 UTC, LucyMerlier requested changes

2021-04-29 13:25 UTC, LucyMerlier commented on src/Controller/TestimoniesController.php
> +            header('Location: /Admin/Testimony/show/' . $id);
/admin/testimony/show/X is not a valid route in simple MVC (has more than 2 parts before parameters)

2021-04-29 14:23 UTC, closed without merging