Devfix before master
WildCodeSchool/orleans-php-202103-project-voyante pull request #126
Opened 2021-04-29 21:38 UTC by RaphaelBS-WCS

fixing dev:
- liens admin_navbar dysfonctionnels dans form add et edit 
(en dehors de la page principale)
- correction des fonctions crud de services

2021-04-29 21:43 UTC, khadimb approved these changes
bien

2021-04-30 06:57 UTC, LucyMerlier requested changes
see comments

2021-04-30 06:57 UTC, LucyMerlier commented on src/Controller/AdminController.php
>              ]);
indentation

2021-04-30 06:57 UTC, LucyMerlier commented on src/View/Admin/Home/Component/_admin_navbar.html.twig
> +                <a class="nav-link" href="/Admin/index/#adminTestimonies">TEMOIGNAGES</a>
you dont need full route to go to an anchor, just #adminService and #adminTestimonies will do

2021-04-30 06:57 UTC, LucyMerlier commented on src/View/Admin/Home/Component/_form_service.html.twig
> +        <textarea name="description" id="description" rows="4" placeholder="Description du services" required>{{ services.description }}</textarea>
"description du services" => service singular

2021-04-30 06:57 UTC, LucyMerlier commented on src/View/Admin/Home/Component/_form_service.html.twig
> -<form action="/Admin/addservice" class="form" method= "POST">
wait... you deleted the opening form tag?...

2021-04-30 06:57 UTC, LucyMerlier commented on src/View/Admin/Services/add_service.html.twig
> +    <form class="form" method= "POST">
... why is the opening form tag here???

2021-04-30 06:57 UTC, LucyMerlier commented on src/View/Admin/Services/edit_service.html.twig
> +        <h2 class="add_service">Editer une prestation</h2>
oh ok I get what you where trying to do. don't to it like that, just put your h2 outside your form and your form tag back into your form component

2021-04-30 07:31 UTC, RaphaelBS-WCS commented on src/Controller/AdminController.php
>              ]);
ok

2021-04-30 07:35 UTC, RaphaelBS-WCS commented on src/View/Admin/Home/Component/_admin_navbar.html.twig
> +                <a class="nav-link" href="/Admin/index/#adminTestimonies">TEMOIGNAGES</a>
ok

2021-04-30 07:38 UTC, RaphaelBS-WCS commented on src/View/Admin/Home/Component/_form_service.html.twig
> +        <textarea name="description" id="description" rows="4" placeholder="Description du services" required>{{ services.description }}</textarea>
ok

2021-04-30 07:58 UTC, RaphaelBS-WCS commented on src/View/Admin/Services/add_service.html.twig
> +    <form class="form" method= "POST">
solved

2021-04-30 07:58 UTC, RaphaelBS-WCS commented on src/View/Admin/Services/edit_service.html.twig
> +        <h2 class="add_service">Editer une prestation</h2>
ok

2021-04-30 07:58 UTC, RaphaelBS-WCS commented on src/View/Admin/Home/Component/_form_service.html.twig
> -<form action="/Admin/addservice" class="form" method= "POST">
yes

2021-04-30 08:02 UTC, khadimb approved these changes
nickel

2021-04-30 08:20 UTC, LucyMerlier requested changes
see comments

2021-04-30 08:20 UTC, LucyMerlier commented on src/Controller/AdminController.php
>              ]);
not resolved

2021-04-30 08:20 UTC, LucyMerlier commented on src/View/Admin/Home/Component/_form_service.html.twig
>      <div>
missing div closing tag or stray div opening tag

2021-04-30 08:29 UTC, RaphaelBS-WCS commented on src/Controller/AdminController.php
>              ]);
Sorry, it's done now.

2021-04-30 08:32 UTC, RaphaelBS-WCS commented on src/View/Admin/Home/Component/_form_service.html.twig
>      <div>
ok

2021-04-30 08:35 UTC, Erdnaxela45 approved these changes

2021-04-30 08:38 UTC, LucyMerlier approved these changes

2021-04-30 08:38 UTC, merged