modif testimonyStatus for validate testimony
WildCodeSchool/orleans-php-202103-project-voyante pull request #166
Opened 2021-05-03 22:50 UTC by Vannou28

2021-05-03 22:53 UTC, RaphaelBS-WCS approved these changes
Approved

2021-05-04 07:32 UTC, LucyMerlier requested changes
see comment

2021-05-04 07:32 UTC, LucyMerlier commented on src/Model/TestimoniesManager.php
> +        $statement->bindValue('id', $testimony['id'], \PDO::PARAM_INT);
do you really need a method to update a whole testimony? wouldn't it be problematic if Nathalie could twist what her clients are saying about her?

2021-05-04 07:58 UTC, RaphaelBS-WCS approved these changes
Approved

2021-05-04 08:00 UTC, LucyMerlier approved these changes

2021-05-04 08:01 UTC, merged