filter testimonies: twig index + adminController index + methode test…
WildCodeSchool/orleans-php-202103-project-voyante pull request #183
Opened 2021-05-04 21:21 UTC by Vannou28

…imoniesManager

2021-05-04 21:49 UTC, RaphaelBS-WCS submitted a review, later dismissed
Approved

2021-05-05 07:33 UTC, RaphaelBS-WCS submitted a review, later dismissed
Approved

2021-05-05 07:48 UTC, LucyMerlier requested changes
guess why ;)

2021-05-05 08:08 UTC, RaphaelBS-WCS approved these changes
Approved

2021-05-05 08:40 UTC, Mcbess-san submitted a review, later dismissed

2021-05-05 08:43 UTC, LucyMerlier requested changes
see comment

2021-05-05 08:43 UTC, LucyMerlier commented on src/View/Admin/Home/Component/_admin_testimony.html.twig
> +    <label for="selectTestimonies">Filtre d'affichage des témoignages</label>
label should be inside of form

2021-05-05 08:50 UTC, RaphaelBS-WCS approved these changes
Approved

2021-05-05 08:52 UTC, LucyMerlier approved these changes

2021-05-05 08:52 UTC, merged