HTML CSS prestations
WildCodeSchool/orleans-php-202103-project-voyante pull request #33
Opened 2021-04-14 14:01 UTC by Erdnaxela45

2021-04-14 14:13 UTC, khadimb commented
revue ok

2021-04-14 14:14 UTC, khadimb approved these changes
revue ok

2021-04-15 08:59 UTC, LucyMerlier requested changes
see comments, also please be coherent when naming branches, and name them correctly

2021-04-15 08:59 UTC, LucyMerlier commented on public/assets/css/style.css
>  }
this may cause conflicts with other PRs. Also avoid magic values

2021-04-15 08:59 UTC, LucyMerlier commented on src/View/Home/index.html.twig
> +</section>
incoherent indentation? sometimes 2 spaces sometimes 4?

2021-04-15 08:59 UTC, LucyMerlier commented on src/View/Home/index.html.twig
> +                    <h3>Formation</h3>
there is a "card-title" class in bootstrap ;)

2021-04-15 09:15 UTC, closed without merging