HTML CSS formulaire
WildCodeSchool/orleans-php-202103-project-voyante pull request #34
Opened 2021-04-14 14:56 UTC by khadimb

2021-04-14 15:02 UTC, Erdnaxela45 approved these changes
Incroyable

2021-04-15 08:54 UTC, LucyMerlier requested changes
see comments

2021-04-15 08:54 UTC, LucyMerlier commented on public/assets/css/contact.css
> +
avoid magic values

2021-04-15 08:54 UTC, LucyMerlier commented on public/assets/css/contact.css
> +    width: calc(100% - 18px);
why?

2021-04-15 08:54 UTC, LucyMerlier commented on src/View/Contact/contact.html.twig
> +                <input class="tel" type="text" name="tel" placeholder="00 00 00 00 00" required>
there is an html type for phone numbers ;)

2021-04-15 08:54 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +            $maxLength = 255;
should be a constant

2021-04-15 08:54 UTC, LucyMerlier commented on src/View/Contact/contact.html.twig
> +                    <option value="cabinet-session">Séance au cabinet</option>
"cabinet-session" => does not sound very british ;)

2021-04-15 08:54 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +                $errors = 'Le prénom doit faire moins de' . $maxLength . ' caractères';
shouldn't there be a space after "de"?

2021-04-15 08:54 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +            }
DON'T ECHO STUFF IN THE CONTROLLER

2021-04-15 08:54 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +        return $this->twig->render('Contact/contact.html.twig');
what if I use "bibi" as subject?

2021-04-15 09:16 UTC, khadimb commented on src/View/Contact/contact.html.twig
> +                    <option value="cabinet-session">Séance au cabinet</option>
this is the right translation

2021-04-15 09:25 UTC, khadimb commented on src/Controller/ContactController.php
> +                $errors = 'Le prénom doit faire moins de' . $maxLength . ' caractères';
ok

2021-04-15 09:32 UTC, khadimb commented on src/Controller/ContactController.php
> +            }
ok

2021-04-15 09:32 UTC, khadimb commented on src/View/Contact/contact.html.twig
> +                <input class="tel" type="text" name="tel" placeholder="00 00 00 00 00" required>
ok

2021-04-15 10:29 UTC, khadimb commented on public/assets/css/contact.css
> +
ok

2021-04-15 10:56 UTC, khadimb commented on public/assets/css/contact.css
> +    width: calc(100% - 18px);
ok

2021-04-15 11:41 UTC, khadimb commented on src/Controller/ContactController.php
> +        return $this->twig->render('Contact/contact.html.twig');
ok

2021-04-15 20:33 UTC, khadimb commented on src/Controller/ContactController.php
> +            $maxLength = 255;
ok

2021-04-16 07:55 UTC, closed without merging