S1 us8 accueil
WildCodeSchool/orleans-php-202103-project-voyante pull request #35
Opened 2021-04-14 14:59 UTC by Vannou28

2021-04-14 20:28 UTC, khadimb submitted a review, later dismissed
revue ok

2021-04-15 08:46 UTC, LucyMerlier requested changes
avoid magic values, also I didn't check them all but are you really using all those images in this single US? oh and finally : be coherent when naming your branches please :)

2021-04-15 08:46 UTC, LucyMerlier commented on public/assets/css/indexHome.css
> +    padding:  30px;
Avoid magic values

2021-04-15 08:46 UTC, LucyMerlier commented on public/assets/css/indexHome.css
> +    padding:  30px;
avoid magic values

2021-04-15 08:46 UTC, LucyMerlier commented on public/assets/css/indexHome.css
> +.h2a{
misclick?

2021-04-15 08:46 UTC, LucyMerlier commented on public/assets/css/indexHome.css
> +    text-shadow: 2px 2px rebeccapurple;
avoid magic values

2021-04-15 08:46 UTC, LucyMerlier commented on public/assets/css/indexHome.css
> +    margin: 20px;
same as above

2021-04-15 08:46 UTC, LucyMerlier commented on public/assets/css/indexHome.css
> +        height: 300px;
idem

2021-04-15 08:46 UTC, LucyMerlier commented on src/View/Home/index.html.twig
> +        <img src="../../assets/images/home/LOGO.png" class="img-fluid" alt="Responsive image">
better use absolute paths

2021-04-15 17:09 UTC, RaphaelBS-WCS reviewed
I left you some comments

2021-04-15 17:09 UTC, RaphaelBS-WCS commented on src/View/Home/index.html.twig
> -    <h1>Nathalie Milliet</h1>
All that must be on your own view sheet

2021-04-15 19:50 UTC, RaphaelBS-WCS reviewed
a last thing...

2021-04-15 19:50 UTC, RaphaelBS-WCS commented on src/View/Home/index.html.twig
> +    <link rel="stylesheet" href="/assets/css/indexHome.css">
it seems to me that it have to be on your home.html.twig instead of here...

2021-04-16 07:46 UTC, RaphaelBS-WCS commented on src/View/Home/index.html.twig
> +    <link rel="stylesheet" href="/assets/css/indexHome.css">
we see together that you have corrected this.

2021-04-16 07:48 UTC, RaphaelBS-WCS submitted a review, later dismissed
I approve!

2021-04-16 08:40 UTC, LucyMerlier requested changes
see comments. also, incoherent branch naming

2021-04-16 08:40 UTC, LucyMerlier commented on public/assets/css/indexHome.css
> +        flex-direction: column;
could use bootstrap to avoid some media queries

2021-04-16 08:40 UTC, LucyMerlier commented on public/assets/css/style.css
> +    --placeholder : #666;
:smiling_imp: 
what's that for though?

2021-04-16 08:40 UTC, LucyMerlier commented on src/View/Home/home.html.twig
> +{% endblock %}
components should not contain twig blocks, and the name of the file should start with an underscore

2021-04-19 08:55 UTC, RaphaelBS-WCS submitted a review, later dismissed
Approved

2021-04-19 12:49 UTC, LucyMerlier requested changes
see comment

2021-04-19 12:49 UTC, LucyMerlier commented on src/View/Home/_home.html.twig
> +                <img src="assets/images/home/LOGO.png" class="img-fluid" alt="Responsive image">
not a valid alt attribute

2021-04-20 10:29 UTC, LucyMerlier requested changes
do you really need all those images for this US? + some of them weigh more than 200KB

2021-04-20 15:00 UTC, RaphaelBS-WCS approved these changes
I approve

2021-04-20 15:21 UTC, LucyMerlier requested changes
purple_nebula.jpg is quite heavy -> possible to make it lighter?

2021-04-21 06:56 UTC, RaphaelBS-WCS approved these changes
It's good to me!

2021-04-21 06:56 UTC, RaphaelBS-WCS commented on public/assets/css/indexHome.css
> +
extra line 4

2021-04-21 07:27 UTC, RaphaelBS-WCS submitted a review, later dismissed
I approve

2021-04-21 07:32 UTC, LucyMerlier submitted a review, later dismissed

2021-04-21 08:29 UTC, RaphaelBS-WCS approved these changes
i approved

2021-04-21 11:28 UTC, LucyMerlier approved these changes

2021-04-21 11:28 UTC, merged