Navbar Done
WildCodeSchool/orleans-php-202103-project-voyante pull request #36
Opened 2021-04-14 16:36 UTC by RaphaelBS-WCS

2021-04-14 16:39 UTC, RaphaelBS-WCS commented on public/assets/css/style.css
> +@import url('https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap');
J'ai remplacé l'url de la police pour avoir tous les effets.

2021-04-14 16:40 UTC, RaphaelBS-WCS commented on public/assets/css/style.css
> -    --font-family : 'Lato', sans-serif;
J'ai enlevé un espace en trop avant les :

2021-04-14 16:43 UTC, Vannou28 approved these changes

2021-04-14 16:44 UTC, Vannou28 submitted a review, later dismissed

2021-04-15 08:40 UTC, LucyMerlier requested changes
avoid magic values and use CSS variables, and be careful with indentation

2021-04-15 08:40 UTC, LucyMerlier commented on src/View/component/_navbar.html.twig
> +{% block javascript %}<script src="https://kit.fontawesome.com/5b0b013c1e.js" crossorigin="anonymous"></script>{% endblock %}
Is it a fluke or are you using 2 spaces for intentation instead of 4?

2021-04-15 08:40 UTC, LucyMerlier commented on public/assets/css/navbar.css
> +    padding-top: 1%;
Avoid magic values

2021-04-15 08:40 UTC, LucyMerlier commented on public/assets/css/navbar.css
> +}
You should avoid magic values

2021-04-15 09:57 UTC, closed without merging