S1_US1_Navbar
WildCodeSchool/orleans-php-202103-project-voyante pull request #38
Opened 2021-04-15 10:03 UTC by RaphaelBS-WCS

I'm sorry, I suppose that the precedent pull request have been removed when i renamed my branch.

2021-04-15 13:17 UTC, Vannou28 submitted a review, later dismissed

2021-04-15 13:38 UTC, LucyMerlier requested changes
see comments

2021-04-15 13:38 UTC, LucyMerlier commented on src/View/component/_navbar.html.twig
> +{% block javascript %}<script src="https://kit.fontawesome.com/5b0b013c1e.js" crossorigin="anonymous"></script>{% endblock %}
2 spaces for indentation? and why not use bootstrap all the way?

2021-04-15 13:38 UTC, LucyMerlier commented on public/assets/css/navbar.css
> +
still a lot of magic values

2021-04-15 13:38 UTC, LucyMerlier commented on public/assets/css/navbar.css
> +}
are media queries really useful here? if you used bootstrap all the way you may not need media queries

2021-04-15 16:57 UTC, RaphaelBS-WCS commented on public/assets/css/navbar.css
> +}
Well, it's ok, the bootstrap navabar is done and all that is no longer there now.

2021-04-15 16:58 UTC, RaphaelBS-WCS commented on public/assets/css/navbar.css
> +
unless I'm mistaken , i've no longer have magic values with my brand new css navbar

2021-04-15 16:59 UTC, RaphaelBS-WCS commented on src/View/component/_navbar.html.twig
> +{% block javascript %}<script src="https://kit.fontawesome.com/5b0b013c1e.js" crossorigin="anonymous"></script>{% endblock %}
Well, the matter come from the visual studio file identifier. I've correct from.

2021-04-15 18:19 UTC, Vannou28 approved these changes
i approuve ;-))

2021-04-16 04:58 UTC, Vannou28 approved these changes
thas is valide!!!

2021-04-16 08:35 UTC, LucyMerlier requested changes
see comments

2021-04-16 08:35 UTC, LucyMerlier commented on public/assets/css/style.css
> +    --width-Middle: 40%;
incoherent naming : use kebab-case

2021-04-16 08:35 UTC, LucyMerlier commented on src/View/component/_navbar.html.twig
> +{% block javascript %}<script src="https://kit.fontawesome.com/5b0b013c1e.js" crossorigin="anonymous"></script>{% endblock %}
should add indentation when opening blocks

2021-04-16 09:37 UTC, RaphaelBS-WCS commented on public/assets/css/style.css
> +    --width-Middle: 40%;
ok we correct it

2021-04-16 09:37 UTC, RaphaelBS-WCS commented on src/View/component/_navbar.html.twig
> +{% block javascript %}<script src="https://kit.fontawesome.com/5b0b013c1e.js" crossorigin="anonymous"></script>{% endblock %}
ok i add it

2021-04-19 09:50 UTC, Vannou28 approved these changes

2021-04-19 09:51 UTC, Vannou28 approved these changes
it's good for me !!!!

2021-04-19 09:52 UTC, Vannou28 submitted a review, later dismissed
it's good for me !!!

2021-04-19 12:47 UTC, LucyMerlier requested changes
see comments

2021-04-19 12:47 UTC, LucyMerlier commented on src/View/component/_navbar.html.twig
> +
empty lines?

2021-04-19 14:02 UTC, RaphaelBS-WCS commented on src/View/component/_navbar.html.twig
> +
erased

2021-04-20 14:23 UTC, Erdnaxela45 submitted a review, later dismissed
Vraiment incroyable

2021-04-21 07:27 UTC, Mcbess-san approved these changes

2021-04-21 07:30 UTC, LucyMerlier approved these changes

2021-04-21 07:31 UTC, merged