html du carousel
WildCodeSchool/orleans-php-202103-project-voyante pull request #39
Opened 2021-04-15 10:13 UTC by Mcbess-san

2021-04-15 13:10 UTC, Vannou28 approved these changes

2021-04-15 13:39 UTC, LucyMerlier requested changes
why are there changes to the composer.lock file?

2021-04-15 17:13 UTC, RaphaelBS-WCS reviewed
I left you some comments

2021-04-15 17:13 UTC, RaphaelBS-WCS commented on src/View/Home/index.html.twig
> +    <h1> Témoignage </h1>
i thought that your section title must not be on the index but on your own view sheet, even if it includes your caroussel.

2021-04-16 04:48 UTC, Vannou28 reviewed
Hi Roman, I have the impression that you deleted the index, is that normal ??? because for me you must have a link in your src / View / Home / testimony.html.twig

2021-04-19 09:47 UTC, RaphaelBS-WCS approved these changes
Approved!

2021-04-19 09:48 UTC, Vannou28 approved these changes

2021-04-19 12:44 UTC, LucyMerlier requested changes
see comments

2021-04-19 12:44 UTC, LucyMerlier commented on src/View/Home/_carousel.html.twig
> +<h2> Témoignage </h2>
spaces before and after text? "témoignage" singular

2021-04-19 12:44 UTC, LucyMerlier commented on src/View/Home/_carousel.html.twig
> +</div>
indentation

2021-04-19 12:44 UTC, LucyMerlier commented on src/View/Home/_carousel.html.twig
> +            je suis ravie et toutes ces prédictions et avertissements se sont avérées utiles et justes. "</p>
spaces before and after text?

2021-04-19 12:44 UTC, LucyMerlier commented on src/View/Home/_carousel.html.twig
> +            <p>" Je recommande Nathalie, qui explique très bien comment elle fonctionne,
hint : there are semantic ways to display quotes in html

2021-04-19 14:36 UTC, Mcbess-san commented on src/View/Home/_carousel.html.twig
> +            je suis ravie et toutes ces prédictions et avertissements se sont avérées utiles et justes. "</p>
yes because i would like too have this présenttion for the text

2021-04-20 14:30 UTC, RaphaelBS-WCS approved these changes
Approved

2021-04-21 07:34 UTC, khadimb approved these changes
yes

2021-04-21 11:49 UTC, LucyMerlier requested changes
indentation, see comments

2021-04-21 11:49 UTC, LucyMerlier commented on src/View/Home/_carousel.html.twig
> +    <div class="carousel-indicators">
indentation inside div

2021-04-21 11:49 UTC, LucyMerlier commented on src/View/Home/_carousel.html.twig
> +        </div>
indentation inside div

2021-04-21 11:49 UTC, LucyMerlier commented on src/View/Home/_carousel.html.twig
> +        </div>
indentation inside div

2021-04-21 11:49 UTC, LucyMerlier commented on src/View/Home/_carousel.html.twig
> +        </div>
indentation inside div

2021-04-21 12:45 UTC, RaphaelBS-WCS submitted a review, later dismissed
I approve

2021-04-21 13:44 UTC, LucyMerlier requested changes
see comment

2021-04-21 13:44 UTC, LucyMerlier commented on src/View/Home/_carousel.html.twig
> +            </div>
too much indentation

2021-04-22 10:39 UTC, RaphaelBS-WCS submitted a review, later dismissed
Approved

2021-04-22 10:42 UTC, khadimb approved these changes
ok

2021-04-22 11:57 UTC, LucyMerlier submitted a review, later dismissed

2021-04-22 14:57 UTC, Vannou28 approved these changes
it's good

2021-04-22 15:23 UTC, LucyMerlier approved these changes

2021-04-22 15:23 UTC, merged