S1 US2 footer
WildCodeSchool/orleans-php-202103-project-voyante pull request #41
Opened 2021-04-15 13:02 UTC by RaphaelBS-WCS

2021-04-15 18:25 UTC, Vannou28 reviewed
raph, in your css code, there are too many magic values

2021-04-16 04:40 UTC, Vannou28 approved these changes

2021-04-16 04:56 UTC, Vannou28 approved these changes
Hi raph, I approve but I will have put your phone image url in style.css so that we can use it later.

2021-04-16 08:32 UTC, LucyMerlier requested changes
see comments

2021-04-16 08:32 UTC, LucyMerlier commented on public/assets/css/footer.css
> +    border-left: 2px solid var(--primary-color);
magic value

2021-04-16 08:32 UTC, LucyMerlier commented on public/assets/css/style.css
> +    --height:80%;
incoherent variable names : use kebab-case

2021-04-16 08:32 UTC, LucyMerlier commented on src/View/component/_footer.html.twig
> +        </div>
empty div

2021-04-16 08:32 UTC, LucyMerlier commented on src/View/component/_footer.html.twig
> +{% endblock %}
this is a component, only made to be included, so it should not contain twig blocks

2021-04-16 08:32 UTC, LucyMerlier commented on src/View/layout.html.twig
> +    {% endblock %}
including block footer in block footer

2021-04-16 10:03 UTC, RaphaelBS-WCS commented on src/View/component/_footer.html.twig
> +        </div>
it was filled by the css background containing the phone image.

2021-04-16 10:03 UTC, RaphaelBS-WCS commented on public/assets/css/style.css
> +    --height:80%;
alright we correct it

2021-04-16 10:03 UTC, RaphaelBS-WCS commented on src/View/component/_footer.html.twig
> +{% endblock %}
i've correct it

2021-04-16 10:03 UTC, RaphaelBS-WCS commented on src/View/layout.html.twig
> +    {% endblock %}
i've correct it

2021-04-20 14:47 UTC, Mcbess-san approved these changes

2021-04-20 15:19 UTC, LucyMerlier requested changes
see comments

2021-04-20 15:19 UTC, LucyMerlier commented on src/View/component/_footer.html.twig
> +    </div>
indentation

2021-04-20 15:19 UTC, LucyMerlier commented on src/View/component/_footer.html.twig
> +        <p>NATHALIE MILLIET</p>
couldn't this be a title?

2021-04-21 06:48 UTC, RaphaelBS-WCS commented on src/View/component/_footer.html.twig
> +        <p>NATHALIE MILLIET</p>
yeah, it could and it will. It's done!

2021-04-21 06:49 UTC, RaphaelBS-WCS commented on src/View/component/_footer.html.twig
> +    </div>
OMG yes Sorry

2021-04-21 07:22 UTC, Mcbess-san approved these changes

2021-04-21 07:28 UTC, LucyMerlier requested changes
see comment

2021-04-21 07:28 UTC, LucyMerlier commented on src/View/component/_footer.html.twig
> +        <h1>NATHALIE MILLIET</h1>
so this will be the only h1 on the entire page?

2021-04-21 07:41 UTC, RaphaelBS-WCS commented on src/View/component/_footer.html.twig
> +        <h1>NATHALIE MILLIET</h1>
yes, we think so... is this a problem?

2021-04-21 08:22 UTC, RaphaelBS-WCS commented on src/View/component/_footer.html.twig
> +        <h1>NATHALIE MILLIET</h1>
i'll transform this in a h2 after adding h1 to navbar

2021-04-21 08:42 UTC, Vannou28 approved these changes
it's good !!!

2021-04-21 11:46 UTC, LucyMerlier submitted a review, later dismissed

2021-04-22 09:21 UTC, LucyMerlier approved these changes

2021-04-22 09:24 UTC, Erdnaxela45 approved these changes
wow

2021-04-22 09:25 UTC, merged