S1 us3 story
WildCodeSchool/orleans-php-202103-project-voyante pull request #42
Opened 2021-04-15 13:04 UTC by Vannou28

story responsive : lien id

2021-04-15 17:04 UTC, RaphaelBS-WCS reviewed
I left you some comments

2021-04-15 17:04 UTC, RaphaelBS-WCS commented on public/assets/css/indexHome.css
> +:root{
All that must be on style.css, especially since  it was imported on line 1

2021-04-15 17:04 UTC, RaphaelBS-WCS commented on public/assets/css/indexHome.css
> +    padding:  30px;
maybe a new css constant?

2021-04-15 17:04 UTC, RaphaelBS-WCS commented on public/assets/css/indexStory.css
> +:root {
same that for home

2021-04-15 19:40 UTC, RaphaelBS-WCS submitted a review, later dismissed
Approved!

2021-04-16 08:00 UTC, LucyMerlier requested changes
see comments

2021-04-19 08:50 UTC, RaphaelBS-WCS submitted a review, later dismissed
Approved

2021-04-19 12:54 UTC, LucyMerlier requested changes
see comments

2021-04-19 12:54 UTC, LucyMerlier commented on src/View/Home/_story.html.twig
> +  <h2 class="storyH2">Qui suis-je?</h2>
not a valid class name

2021-04-19 12:54 UTC, LucyMerlier commented on src/View/Home/_story.html.twig
> +                <img src="assets/images/story/photo_nathalie2.webp" class="img-fluid" alt="Responsive image">
not a valid alt attribute

2021-04-20 10:27 UTC, LucyMerlier requested changes
see comments + all those images? do you need them all for this US? + 4 of them weigh more than 200KB

2021-04-20 10:27 UTC, LucyMerlier commented on src/View/Home/_story.html.twig
> +                    <a href="/History/index">En savoir+</a>
no uppercase in routes

2021-04-20 10:27 UTC, LucyMerlier commented on public/assets/css/style.css
> +    --border-radius:4px;
has not been changed

2021-04-20 10:27 UTC, LucyMerlier commented on public/assets/css/style.css
> +    --placeholder : #666;
there shouldnt be spaces before colon

2021-04-20 14:57 UTC, RaphaelBS-WCS approved these changes
Approved

2021-04-21 08:44 UTC, RaphaelBS-WCS approved these changes
Approved

2021-04-21 11:43 UTC, LucyMerlier submitted a review, later dismissed

2021-04-22 10:27 UTC, RaphaelBS-WCS approved these changes
Approved

2021-04-22 10:28 UTC, LucyMerlier approved these changes

2021-04-22 10:28 UTC, merged