S1 us6 formulaire
WildCodeSchool/orleans-php-202103-project-voyante pull request #43
Opened 2021-04-15 21:45 UTC by khadimb

2021-04-16 04:38 UTC, Vannou28 reviewed
hello khadim, I'm sorry but you have too many magic values and the import of the font family in the css should be in the .css style.
sorry ;-(((

2021-04-19 08:47 UTC, RaphaelBS-WCS submitted a review, later dismissed
I approve

2021-04-19 09:45 UTC, RaphaelBS-WCS submitted a review, later dismissed
Approve

2021-04-19 09:47 UTC, Vannou28 approved these changes
it's good for me!!!

2021-04-19 09:58 UTC, LucyMerlier requested changes
see comments

2021-04-19 09:58 UTC, LucyMerlier commented on public/assets/css/contact.css
> +
There are still magic values here and there that could have been avoided

2021-04-19 09:58 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +        }
incoherent error messages

2021-04-19 09:58 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +
and what if there are no errors?

2021-04-19 09:58 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +            if (empty($data['subject'])) {
are there no other validations on the subject?

2021-04-19 09:58 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +            }
email length?

2021-04-19 09:58 UTC, LucyMerlier commented on src/View/Contact/contact.html.twig
> +    <form action="/contact/index" class="form" method= "POST" novalidate>
novalidate?

2021-04-19 10:20 UTC, khadimb commented on src/View/Contact/contact.html.twig
> +    <form action="/contact/index" class="form" method= "POST" novalidate>
ok

2021-04-19 10:31 UTC, khadimb commented on src/Controller/ContactController.php
> +        }
ok

2021-04-19 10:32 UTC, khadimb commented on public/assets/css/contact.css
> +
ok

2021-04-19 11:27 UTC, khadimb commented on src/Controller/ContactController.php
> +
ok

2021-04-19 14:06 UTC, khadimb commented on src/Controller/ContactController.php
> +            }
Ok

2021-04-19 14:31 UTC, khadimb commented on src/Controller/ContactController.php
> +            if (empty($data['subject'])) {
ok

2021-04-20 14:26 UTC, RaphaelBS-WCS approved these changes
Approved

2021-04-21 07:58 UTC, Mcbess-san approved these changes

2021-04-21 11:42 UTC, LucyMerlier requested changes
see comments

2021-04-21 11:42 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +            define('MAX_LENGTH_EMAIL', 320);
you're working in OOP, these constants could be class constants :)

2021-04-21 11:42 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +            $this->setCheckWordPresenceInArray($data['subject'], $subjects, 'Le sujet saisie n\'est pas valable');
typo "saisi"

2021-04-21 11:42 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +            $this->setCheckFilterValidateEmail($data['email'], 'Mauvais format d\'email');
incoherent error messages

2021-04-21 11:42 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +            }
what is this wild echo doing in a controller?

2021-04-21 11:42 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +}
all those methods should be private if you want to let them in this class
+ warning, your class will soon have more than 10 methods => too much. Maybe refactor and put those methods in their own class?

2021-04-21 11:42 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +        var_dump($word);
var_dump?

2021-04-21 11:42 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +    public function setCheckWordPresenceInArray(string $word, array $array, string $message)
why "set" keywords at the start of the methods names? these are not setters

2021-04-21 11:42 UTC, LucyMerlier commented on src/View/Contact/contact.html.twig
> +    <form action="/contact/index" class="form" method= "POST" novalidate>
no i meant, you probably don't want to keep this novalidate here

2021-04-21 11:42 UTC, LucyMerlier commented on src/View/Contact/contact.html.twig
> +        <div class="buttoncontact">
use kebab-case for class names

2021-04-21 11:49 UTC, khadimb commented on src/Controller/ContactController.php
> +        var_dump($word);
ok

2021-04-21 11:50 UTC, khadimb commented on src/View/Contact/contact.html.twig
> +        <div class="buttoncontact">
ok

2021-04-21 12:34 UTC, khadimb commented on src/View/Contact/contact.html.twig
> +        <div class="buttoncontact">
ok

2021-04-21 12:35 UTC, khadimb commented on src/Controller/ContactController.php
> +        var_dump($word);
ok

2021-04-21 12:37 UTC, khadimb commented on src/Controller/ContactController.php
> +            $this->setCheckWordPresenceInArray($data['subject'], $subjects, 'Le sujet saisie n\'est pas valable');
ok

2021-04-21 12:42 UTC, khadimb commented on src/Controller/ContactController.php
> +            }
ok

2021-04-21 12:58 UTC, khadimb commented on src/Controller/ContactController.php
> +    public function setCheckWordPresenceInArray(string $word, array $array, string $message)
ok

2021-04-21 13:05 UTC, khadimb commented on src/Controller/ContactController.php
> +}
ok

2021-04-21 13:14 UTC, khadimb commented on src/Controller/ContactController.php
> +            define('MAX_LENGTH_EMAIL', 320);
ok

2021-04-21 17:39 UTC, khadimb commented on src/Controller/ContactController.php
> +            define('MAX_LENGTH_EMAIL', 320);
ok

2021-04-21 17:39 UTC, khadimb commented on src/Controller/ContactController.php
> +            $this->setCheckFilterValidateEmail($data['email'], 'Mauvais format d\'email');
ok

2021-04-22 09:52 UTC, Vannou28 submitted a review, later dismissed
that is good !!!!

2021-04-22 10:22 UTC, RaphaelBS-WCS submitted a review, later dismissed
Approve

2021-04-22 12:06 UTC, LucyMerlier requested changes

2021-04-22 12:06 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +            $this->checkSentenceEmpty($data['email'], 'L\'email est obligatoire');
incoherent error messages

2021-04-22 12:06 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +                . self::MAX_LENGTH_EMAIL . ' caractères');
incoherent error messages

2021-04-22 12:06 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +            $this->checkFilterValidateEmail($data['email'], 'Mauvais format d\'email');
incoherent error messages

2021-04-22 12:06 UTC, LucyMerlier commented on src/Controller/ContactController.php
> +    }
no return typehint for all you form checkers?

2021-04-22 12:06 UTC, LucyMerlier commented on src/View/Contact/contact.html.twig
> +            <input class="tel" type="tel" name="tel" size="10" placeholder="00 00 00 00 00" required>
size 10 but your placeholder is 14 characters long?

2021-04-22 12:06 UTC, LucyMerlier commented on src/View/Contact/contact.html.twig
> +            <button type="submit" href="">Envoyer</button>
why href?

2021-04-22 12:11 UTC, khadimb commented on src/Controller/ContactController.php
> +    private const MAX_LENGTH_EMAIL = 320;
ok

2021-04-22 12:17 UTC, khadimb commented on src/View/Contact/contact.html.twig
> +            <input class="tel" type="tel" name="tel" size="10" placeholder="00 00 00 00 00" required>
ok

2021-04-22 12:17 UTC, khadimb commented on src/View/Contact/contact.html.twig
> +            <button type="submit" href="">Envoyer</button>
error ok

2021-04-22 12:24 UTC, khadimb commented on src/Controller/ContactController.php
> +            $this->checkSentenceEmpty($data['email'], 'L\'email est obligatoire');
ok

2021-04-22 12:24 UTC, khadimb commented on src/Controller/ContactController.php
> +                . self::MAX_LENGTH_EMAIL . ' caractères');
ok

2021-04-22 12:24 UTC, khadimb commented on src/Controller/ContactController.php
> +            $this->checkFilterValidateEmail($data['email'], 'Mauvais format d\'email');
ok

2021-04-22 21:14 UTC, khadimb commented on src/Controller/ContactController.php
> +                return 'Votre message à bien été envoyé.';
ok

2021-04-23 08:34 UTC, khadimb commented on src/Controller/ContactController.php
> +    }
ok

2021-04-23 09:10 UTC, Mcbess-san submitted a review, later dismissed

2021-04-26 08:38 UTC, LucyMerlier requested changes
see comment

2021-04-26 08:38 UTC, LucyMerlier commented on src/View/Contact/success.html.twig
> +            </form>
a form? shouldn't this be a link?

2021-04-26 12:49 UTC, RaphaelBS-WCS submitted a review, later dismissed
Approved!

2021-04-27 07:01 UTC, LucyMerlier requested changes
see comments

2021-04-27 07:01 UTC, LucyMerlier commented on src/View/Contact/success.html.twig
> +            <a href="http://localhost:8000/" class="button-contact">
NO! your route starts at the first "/" from your domain / host => if you want a link to go back to home page, just put "/" in href!

2021-04-27 14:05 UTC, khadimb commented on src/View/Contact/success.html.twig
> +                <button type="submit">Accueil</button>
ok

2021-04-27 14:05 UTC, khadimb commented on src/View/Contact/success.html.twig
> +            <a href="http://localhost:8000/" class="button-contact">
ok

2021-04-27 14:23 UTC, RaphaelBS-WCS approved these changes
Approved

2021-04-27 15:23 UTC, LucyMerlier approved these changes

2021-04-27 15:23 UTC, merged