S01 us4 prestations html css
WildCodeSchool/orleans-php-202103-project-voyante pull request #53
Opened 2021-04-20 14:36 UTC by Erdnaxela45

2021-04-20 14:43 UTC, RaphaelBS-WCS submitted a review, later dismissed
Approved

2021-04-20 15:13 UTC, LucyMerlier requested changes
indentation

2021-04-20 15:13 UTC, LucyMerlier commented on src/View/Home/_prestations.html.twig
> +        </div>
indentation?

2021-04-21 08:00 UTC, Mcbess-san approved these changes

2021-04-21 08:21 UTC, Mcbess-san approved these changes

2021-04-21 08:22 UTC, Mcbess-san approved these changes

2021-04-21 11:29 UTC, LucyMerlier approved these changes

2021-04-21 12:58 UTC, RaphaelBS-WCS approved these changes
Approved

2021-04-21 13:38 UTC, LucyMerlier approved these changes

2021-04-21 13:38 UTC, merged