S02 us5 bdd
WildCodeSchool/orleans-php-202103-project-voyante pull request #55
Opened 2021-04-21 15:22 UTC by Mcbess-san

2021-04-22 14:14 UTC, RaphaelBS-WCS approved these changes
Approved

2021-04-22 15:19 UTC, LucyMerlier requested changes

2021-04-22 15:19 UTC, LucyMerlier commented on src/View/Home/_carousel.html.twig
> +                <img src="/assets/images/592367.jpg" class="d-block w-100 h-100" alt="...">
images naming + "..." is not a valid alt attribute

2021-04-24 08:30 UTC, RaphaelBS-WCS requested changes
See Comments

2021-04-24 08:30 UTC, RaphaelBS-WCS commented on public/assets/css/testimony.css
> +        font-size: 10px;
magic values

2021-04-24 08:30 UTC, RaphaelBS-WCS commented on public/assets/css/testimony.css
> +        font-size: 10px;
Magic Values

2021-04-27 09:44 UTC, closed without merging