S2 us3 view story
WildCodeSchool/orleans-php-202103-project-voyante pull request #57
Opened 2021-04-22 08:49 UTC by Vannou28

2021-04-22 10:25 UTC, RaphaelBS-WCS submitted a review, later dismissed
Approved

2021-04-22 12:11 UTC, LucyMerlier requested changes
see comments

2021-04-22 12:11 UTC, LucyMerlier commented on src/View/History/index.html.twig
> +                    <img src="../assets/images/history/8ans.webp" class="img-fluid" alt="Responsive image">
alt="Responsive image" => not a valid alt

2021-04-22 12:11 UTC, LucyMerlier commented on src/View/History/index.html.twig
> +                    <img src="../assets/images/history/9-20ans.webp" class="img-fluid" alt="Responsive image">
same as above

2021-04-22 12:11 UTC, LucyMerlier commented on src/View/History/index.html.twig
> +                    <img src="../assets/images/history/30ans.webp" class="img-fluid" alt="Responsive image">
same as above

2021-04-22 12:11 UTC, LucyMerlier commented on src/View/History/index.html.twig
> +                    <img src="../assets/images/history/42ans.jpg" class="img-fluid" alt="Responsive image">
same as above

2021-04-22 12:11 UTC, LucyMerlier commented on src/View/History/index.html.twig
> +    <section class="fullStory" id="story">
use kebab-case for classnames

2021-04-22 12:11 UTC, LucyMerlier commented on src/Controller/HistoryController.php
> +}
is it really necessary to have a dedicated controller just for this page?

2021-04-22 15:06 UTC, Vannou28 commented on src/Controller/HistoryController.php
> +}
I will modify it this weekend if you see at the level of the controller

2021-04-23 20:23 UTC, Vannou28 commented on src/Controller/HistoryController.php
> +}
the page is transferred to the HomeControler the link in the index story is changed and transferred. vannou28

2021-04-24 08:17 UTC, RaphaelBS-WCS approved these changes
Approved

2021-04-26 08:41 UTC, LucyMerlier approved these changes

2021-04-26 08:41 UTC, merged