S02 us4 twig formation
WildCodeSchool/orleans-php-202103-project-voyante pull request #60
Opened 2021-04-22 14:12 UTC by Erdnaxela45

2021-04-23 14:29 UTC, RaphaelBS-WCS approved these changes
Approved

2021-04-25 15:49 UTC, LucyMerlier requested changes
see comments + it looks like there are 2 user stories here (training and services) + please use english even for class names, image names, adn folder names + all your images are too heavy

2021-04-25 15:49 UTC, LucyMerlier commented on public/assets/css/formation.css
> +}
english?

2021-04-25 15:49 UTC, LucyMerlier commented on src/View/Formation/index.html.twig
> +                </div>
this very much looks like a list

2021-04-25 15:49 UTC, LucyMerlier commented on src/View/Formation/index.html.twig
> +                <img src="../assets/images/protection.jpg" class="img-fluid" alt="">
alt attribute is mandatory

2021-04-25 15:49 UTC, LucyMerlier commented on src/View/Formation/index.html.twig
> +            </div>
this looks like a list

2021-04-25 15:49 UTC, LucyMerlier commented on src/View/Formation/index.html.twig
> +                <img src="../assets/images/esprits.jpg" class="img-fluid" alt="">
alt attribute is mandatory

2021-04-25 15:49 UTC, LucyMerlier commented on src/View/Formation/index.html.twig
> +            </div>
list?

2021-04-25 15:49 UTC, LucyMerlier commented on src/View/Formation/index.html.twig
> +                <img src="../assets/images/magie.jpg" class="img-fluid" alt="">
alt?

2021-04-25 15:49 UTC, LucyMerlier commented on src/View/Formation/index.html.twig
> +            </div>
list?

2021-04-25 15:49 UTC, LucyMerlier commented on src/View/Formation/index.html.twig
> +                <img src="../assets/images/culture.jpg" class="img-fluid" alt="">
alt?

2021-04-25 15:49 UTC, LucyMerlier commented on src/View/Home/_prestations.html.twig
> +                        <li class="list-group-item">Tarif 30 minutes : {{ prestation.price30min }} €</li>
what if there is no 30min price?

2021-04-25 15:49 UTC, LucyMerlier commented on src/View/Home/_prestations.html.twig
>              <div class="card" style="width: 18rem;">
NO STYLE IN HTML

2021-04-26 14:28 UTC, closed without merging