S2 admin Structur
WildCodeSchool/orleans-php-202103-project-voyante pull request #66
Opened 2021-04-23 12:56 UTC by RaphaelBS-WCS

setting up triple layout structure to prepare Admin part of the website

2021-04-23 13:17 UTC, Erdnaxela45 approved these changes

2021-04-23 13:23 UTC, LucyMerlier requested changes
17 files changed??

2021-04-23 14:49 UTC, Mcbess-san commented on src/View/component/_admin_navbar.html.twig
> +            <h1>NATHALIE VOYANCE</h1>
change h1

2021-04-23 14:50 UTC, Mcbess-san requested changes
check the comment

2021-04-27 10:41 UTC, closed without merging

2021-04-27 10:42 UTC, RaphaelBS-WCS commented
this pull request was replace by many others to make less files changes att a time.