Us13 15 model manager bd
WildCodeSchool/orleans-php-202103-project-voyante pull request #76
Opened 2021-04-23 22:16 UTC by Vannou28

2021-04-24 08:22 UTC, RaphaelBS-WCS approved these changes
Good Work

2021-04-27 09:09 UTC, Erdnaxela45 approved these changes

2021-04-27 11:50 UTC, LucyMerlier requested changes
see comment + there is a whole CRUD in your controller, which are 5 different user stories ;)

2021-04-27 11:50 UTC, LucyMerlier commented on src/Controller/TestimonyController.php
> +     * List Testimonys
singular : testimony => plural : testimonIEs ;)

2021-04-28 08:17 UTC, RaphaelBS-WCS commented
replace by others

2021-04-28 08:17 UTC, closed without merging