class validation of form and generation of errors in html format
WildCodeSchool/orleans-php-202103-project-voyante pull request #77
Opened 2021-04-25 10:16 UTC by Vannou28

class made to control and validate case for form view

2021-04-26 08:06 UTC, khadimb submitted a review, later dismissed
nickel

2021-04-26 08:54 UTC, LucyMerlier requested changes
see comments

2021-04-26 08:54 UTC, LucyMerlier commented on README class FormValidation.txt
> +}
what's this file doing here?

2021-04-26 08:54 UTC, LucyMerlier commented on src/Services/FormValidation.php
> +namespace App\Services;
good practive is to use singular ("App\Service" and "src/Service")

2021-04-26 08:54 UTC, LucyMerlier commented on src/Services/FormValidation.php
> +    }
why does this method return a bool when all the others return void?

2021-04-26 08:54 UTC, LucyMerlier commented on src/Services/FormValidation.php
> +    }
this looks like it doesn't set errors, it looks like it adds an error ;)

2021-04-26 08:54 UTC, LucyMerlier commented on src/Services/FormValidation.php
> +    }
?

2021-04-26 08:54 UTC, LucyMerlier commented on src/Services/FormValidation.php
> +    }
you should not handle html tags outside of twig templates

2021-04-26 08:54 UTC, LucyMerlier commented on src/Services/FormValidation.php
> +    protected array $errors = [];
why is it protected? your class does not have any child class?

2021-04-26 10:23 UTC, Vannou28 commented on README class FormValidation.txt
> +}
c'est pour les copians

2021-04-26 10:24 UTC, Vannou28 commented on src/Services/FormValidation.php
> +namespace App\Services;
si on fait plusieurs services !!!

2021-04-26 10:25 UTC, Vannou28 commented on src/Services/FormValidation.php
> +    }
car j'en est besoin en bool

2021-04-26 10:26 UTC, Vannou28 commented on src/Services/FormValidation.php
> +    }
on enregistre une erreur dans un tableau donc on fait un set

2021-04-26 10:26 UTC, Vannou28 commented on src/Services/FormValidation.php
> +    }
ca peut servir ;-)))

2021-04-26 10:27 UTC, Vannou28 commented on src/Services/FormValidation.php
> +    }
je trouvais ça pratique pour les copains

2021-04-26 10:27 UTC, Vannou28 commented on src/Services/FormValidation.php
> +    protected array $errors = [];
ok je vais le mettre le private

2021-04-27 09:12 UTC, Erdnaxela45 approved these changes

2021-04-27 11:44 UTC, LucyMerlier approved these changes

2021-04-27 11:44 UTC, merged